package view;

import database.koneksi;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DashboardView extends javax.swing.JPanel {

    public DashboardView() throws SQLException, ClassNotFoundException {
        initComponents();
        koneksi.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel2 = new widget.Panel();
        b_film = new widget.Button();
        b_studio = new widget.Button();
        b_jadwal = new widget.Button();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        b_film.setText("FILM");
        b_film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_filmActionPerformed(evt);
            }
        });

        b_studio.setText("STUDIO");
        b_studio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_studioActionPerformed(evt);
            }
        });

        b_jadwal.setText("JADWAL");
        b_jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_jadwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(b_film, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(b_studio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(b_jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 214, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_film, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_studio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jPanel1.add(panel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void b_filmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_filmActionPerformed
        try {
            showFilmView();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(DashboardView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_filmActionPerformed

    private void b_studioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_studioActionPerformed
        try {
            showStudioView();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(DashboardView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_studioActionPerformed

    private void b_jadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_jadwalActionPerformed
        try {
            showJadwalView();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(DashboardView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_jadwalActionPerformed
    private void showFilmView() throws SQLException, ClassNotFoundException {
        jPanel1.removeAll();
        jPanel1.add(new FilmView());
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    private void showStudioView() throws SQLException, ClassNotFoundException {
        jPanel1.removeAll();
        jPanel1.add(new StudioVIew());
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    private void showJadwalView() throws SQLException, ClassNotFoundException {
        jPanel1.removeAll();
        jPanel1.add(new JadwalView());
        jPanel1.revalidate();
        jPanel1.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button b_film;
    private widget.Button b_jadwal;
    private widget.Button b_studio;
    private javax.swing.JPanel jPanel1;
    private widget.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
